import './commandsExemploBasico/commands'
import './commandsExemploIntermediario/gui_commands'
import './commandsExemploIntermediario/api_commands'
import './commandsExemploIntermediario/cli_commands'
import './commandsExemploAvancado/commands'
import '@percy/cypress'
import 'cypress-plugin-snapshots/commands'
